# Generated by Django 4.2.2 on 2023-06-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_rename_years_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('rg', 'Regular'), ('sr', 'Senior')], default='jr', max_length=25),
            preserve_default=False,
        ),
    ]
