# Generated by Django 4.2.2 on 2023-06-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alter_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-age',)},
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
