# Generated by Django 4.2.2 on 2023-06-23 23:32

from django.db import migrations
from django.utils.text import slugify


def add_slugs(apps, schema_editor):
    University = apps.get_model('models_app', 'University')
    universities = University.objects.all()

    for university in universities:
        university.slug = slugify(university.name)

    University.objects.bulk_update(universities, ['slug'])


def delete_slugs(apps, schema_editor):
    University = apps.get_model('models_app', 'University')
    universities = University.objects.all()

    for university in universities:
        university.slug = None

    University.objects.bulk_update(universities, ['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_alter_student_options_university_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, delete_slugs)
    ]
