# Generated by Django 4.2.2 on 2023-06-29 01:52

import Forms_Part2.forms_app2.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25, validators=[Forms_Part2.forms_app2.validators.validate_text])),
                ('priority', models.IntegerField(validators=[Forms_Part2.forms_app2.validators.validate_priority])),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
