# Generated by Django 4.2.2 on 2023-06-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidateModel',
            new_name='Todo',
        ),
    ]
