# Generated by Django 4.2.2 on 2023-06-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app2', '0002_rename_validatemodel_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms_app2.person'),
            preserve_default=False,
        ),
    ]
