# Generated by Django 4.2.2 on 2023-06-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app2', '0003_person_todo_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
