# Generated by Django 4.2.4 on 2023-08-15 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_play_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
