# Generated by Django 4.2.4 on 2023-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
