# Generated by Django 4.2.4 on 2023-08-13 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MaxLengthValidator(2)])),
                ('last_name', models.CharField(max_length=25, validators=[django.core.validators.MaxLengthValidator(2)])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(8)])),
                ('image', models.URLField()),
                ('age', models.PositiveIntegerField(blank=True, default=18)),
            ],
        ),
    ]
