# Generated by Django 4.2.4 on 2023-08-13 09:36

import Frutipedia.fruit_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(2), Frutipedia.fruit_app.models.only_letters_validator])),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True)),
            ],
        ),
    ]
