# Generated by Django 4.2.4 on 2023-08-13 10:45

import Frutipedia.fruit_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0002_fruitmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), Frutipedia.fruit_app.models.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
