# Generated by Django 4.2.4 on 2023-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0003_alter_fruitmodel_name_alter_profilemodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
