# Generated by Django 4.2.4 on 2023-08-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0004_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='image',
            field=models.URLField(),
        ),
    ]
