# Generated by Django 4.2.2 on 2023-06-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
