# Generated by Django 4.2.2 on 2023-06-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_demo_app', '0002_person_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
