# Generated by Django 4.2.2 on 2023-06-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_demo_app', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Student',
        ),
    ]
